# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-21 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='comments',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
